### ISSUE TITLE
Ant build file didn't make anything runable

### ISSUE THREAD

**Issue by chriscamacho** [phwoelfel/KSPSavefileEditor#5]
After manually compiling and running, was able load copy and paste KIS inventory between two kerbins and load the save into the game fine...

Its more than two years since a commit, would I be wasting my time making a PR with a better build.xml ?

**Comment by phwoelfel** [comment]
As you mentioned I haven't done anything in the last two years and I don't really have time to make any enhancements anytime soon. I would still be happy to merge your PR if you are willing to fix the build.xml!

**Comment by chriscamacho** [comment]
okay let me look (I have to remember how its done now!)

**Comment by chriscamacho** [comment]
https://github.com/phwoelfel/KSPSavefileEditor/pull/6
